/* Automatically generated by './build/build-entry.js' */
/* eslint-disable */
import '~/src/theme/global/base.scss'
/* components */
import VAffix from '~/src/components/affix'
import VButton from '~/src/components/button'
import VCheckBox from '~/src/components/check-box'
import VCollapse from '~/src/components/collapse'
import VDatetime from '~/src/components/datetime'
import VDialog from '~/src/components/dialog'
import VDrawer from '~/src/components/drawer'
import VField from '~/src/components/field'
import VForm from '~/src/components/form'
import VImg from '~/src/components/img'
import VLazy from '~/src/components/lazy'
import VLink from '~/src/components/link'
import VNavbar from '~/src/components/navbar'
import VNoticebar from '~/src/components/noticebar'
import VPicker from '~/src/components/picker'
import VRange from '~/src/components/range'
import VRender from '~/src/components/render'
import VScroller from '~/src/components/scroller'
import VSearch from '~/src/components/search'
import VSlidingdrawer from '~/src/components/slidingdrawer'
import VStep from '~/src/components/step'
import VSwipe from '~/src/components/swipe'
import VSwitcher from '~/src/components/switcher'
import VToggle from '~/src/components/toggle'
import VUploader from '~/src/components/uploader'
/* prototypes */
import VAlert from '~/src/prototypes/alert'
import VCache from '~/src/prototypes/cache'
import VDebug from '~/src/prototypes/debug'
import VOverlay from '~/src/prototypes/overlay'
import VScrolly from '~/src/prototypes/scrolly'
import VToast from '~/src/prototypes/toast'
/* directives */
import VLazyload from '~/src/directives/lazyload'
/* transition */
import VCollapseTransition from '~/src/transition/collapseTransition'

const components = [
  VAffix,
  VButton,
  VCheckBox,
  VCollapse,
  VDatetime,
  VDialog,
  VDrawer,
  VField,
  VForm,
  VImg,
  VLazy,
  VLink,
  VNavbar,
  VNoticebar,
  VPicker,
  VRange,
  VRender,
  VScroller,
  VSearch,
  VSlidingdrawer,
  VStep,
  VSwipe,
  VSwitcher,
  VToggle,
  VUploader
]

const directives = [
  VLazyload
]

const isClient = typeof window !== 'undefined'
const install = function(Vue, opts = {}) {
  const conf = {
    md: opts.md === undefined ? false : opts.md
  }

  Vue.prototype.$sakura = conf

  if (isClient) {
    Vue.prototype.$toast = VToast(conf)

    Vue.prototype.$alert = VAlert(conf)

    Vue.prototype.$cache = VCache

    Vue.prototype.$scrollY = VScrolly

    Vue.prototype.$overlay = VOverlay

    Vue.prototype.$debug = VDebug
  }

  directives.forEach((directive) => {
    Vue.use(directive)
  })

  components.forEach((component) => {
    Vue.component(component.name, component)
  })
}
/* istanbul ignore if */
if (isClient && window.Vue) {
  install(window.Vue)
}

export default {
  version: '2.19.3',
  install,
  VAffix,
  VButton,
  VCheckBox,
  VCollapse,
  VDatetime,
  VDialog,
  VDrawer,
  VField,
  VForm,
  VImg,
  VLazy,
  VLink,
  VNavbar,
  VNoticebar,
  VPicker,
  VRange,
  VRender,
  VScroller,
  VSearch,
  VSlidingdrawer,
  VStep,
  VSwipe,
  VSwitcher,
  VToggle,
  VUploader,
  VAlert,
  VCache,
  VDebug,
  VOverlay,
  VScrolly,
  VToast,
  VLazyload,
  VCollapseTransition
}
